# Generated by Django 2.1.8 on 2019-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('age', models.IntegerField(default=10, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '人类模型',
                'verbose_name_plural': '人类模型',
            },
        ),
        migrations.CreateModel(
            name='Plant_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='树名')),
                ('age', models.IntegerField(default=10, verbose_name='树龄')),
            ],
            options={
                'verbose_name': '植物模型',
                'verbose_name_plural': '植物模型',
            },
        ),
    ]
