# Generated by Django 2.1.8 on 2019-06-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'question',
            },
        ),
        migrations.AlterModelOptions(
            name='man_model',
            options={'verbose_name': 'man', 'verbose_name_plural': 'man'},
        ),
        migrations.AlterModelOptions(
            name='plant_model',
            options={'verbose_name': 'plant', 'verbose_name_plural': 'plant'},
        ),
        migrations.AddField(
            model_name='plant_model',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Man_Model'),
        ),
        migrations.AlterField(
            model_name='man_model',
            name='age',
            field=models.IntegerField(default=10, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='man_model',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='age',
            field=models.IntegerField(default=10, verbose_name='p_age'),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='name',
            field=models.CharField(max_length=20, verbose_name='p_name'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
