# Generated by Django 2.1.8 on 2019-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_person_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
    ]
