# Generated by Django 2.1.7 on 2019-07-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
